# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - socialhubmern

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install packages - server
        run: |
          cd server
          npm install

      - name: npm install packages, build then copy files - client
        run: |
          cd client
          npm install
          npm run build
          cp -r build ../server/public

      - name: Zip files for deployment
        run: |
          zip -r release.zip . -x "*node_modules/*" "*/.git/*" "client/node_modules/*" "client/src/*" "client/public/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D1DD85D517494B7D868C3DEBD9937B5A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AEF45EC20FBC4DD1A07815236BD403A3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7DDC91D9D5794D2893E349A5F86FBF79 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'socialhubmern'
          slot-name: 'Production'
          package: .
          
